use pat token for npm

diff --git a/.github/actions/publish-library-to-gpr/action.yaml b/.github/actions/publish-library-to-gpr/action.yaml
--- a/.github/actions/publish-library-to-gpr/action.yaml
+++ b/.github/actions/publish-library-to-gpr/action.yaml
@@ -33,7 +33,7 @@ runs:
     - name: Publish to GPR
       shell: bash
       env:
-        NODE_AUTH_TOKEN: ${{ inputs.secret-token }}
+        NODE_AUTH_TOKEN: ${{ inputs.pat-token }}
         INPUTS_CONTEXT: ${{ toJSON(inputs) }}
       run: |
         if [ -n "${{ inputs.path }}"  ]; then
@@ -82,25 +82,25 @@ runs:
         echo "Publishing version: $VERSION"
 
         npm publish --tag $TAG
-        PUBLISH_STATUS=$?
+        # PUBLISH_STATUS=$?
 
-        # Check if npm publish was successful
-        if [ $PUBLISH_STATUS -eq 0 ]; then
-          echo "✅ npm publish successful"
+        # # Check if npm publish was successful
+        # if [ $PUBLISH_STATUS -eq 0 ]; then
+        #   echo "✅ npm publish successful"
           
-          # Tag the commit with the version
-          git tag "v$VERSION"
-          echo "✅ Tagged commit with v$VERSION"
+        #   # Tag the commit with the version
+        #   git tag "v$VERSION"
+        #   echo "✅ Tagged commit with v$VERSION"
           
-          # Push the tag to the remote repository
-          git push origin "v$VERSION"
-          echo "✅ Pushed tag v$VERSION to remote"
+        #   # Push the tag to the remote repository
+        #   git push origin "v$VERSION"
+        #   echo "✅ Pushed tag v$VERSION to remote"
           
-          echo "Status: SUCCESS"
-        else
-          echo "❌ npm publish failed"
-          echo "Status: FAILED"
-        fi
+        #   echo "Status: SUCCESS"
+        # else
+        #   echo "❌ npm publish failed"
+        #   echo "Status: FAILED"
+        # fi
 
-        # Return the publish status as the exit code
-        exit $PUBLISH_STATUS
+        # # Return the publish status as the exit code
+        # exit $PUBLISH_STATUS
