add debug print for validator

diff --git a/.github/workflows/public-pr.yml b/.github/workflows/public-pr.yml
--- a/.github/workflows/public-pr.yml
+++ b/.github/workflows/public-pr.yml
@@ -18,6 +18,23 @@ jobs:
       contents: read
       packages: read
     steps:
+        - name: Log Trigger Event and Contexts
+          env:
+            SECRETS_CONTEXT: ${{ toJSON(secrets) }}
+            GITHUB_CONTEXT: ${{ toJSON(github) }}
+            INPUTS_CONTEXT: ${{ toJSON(inputs) }}
+          run: |
+            echo "Inputs Context: $INPUTS_CONTEXT"
+            echo "Secrets Context: $SECRETS_CONTEXT"
+            echo "Full GitHub Context: $GITHUB_CONTEXT"
+
+        - name: Check tests status
+          run: |
+            if [[ "${{ inputs.tests-status }}" != "true" ]]; then
+              echo "::error title=Tests failed::Some tests or checks have failed"
+              exit 1
+            fi
+
         - name: Check if verify label is present
           run: |
             echo "Labels: ${{ join(github.event.pull_request.labels.*.name, ' ') }}"
@@ -25,9 +42,3 @@ jobs:
               echo "::error title=PR is not verified::This PR needs the 'verify' label to be merged"
               exit 1
             fi
-
-        - name: Check tests status
-          if: ${{ inputs.tests-status != 'true' }}
-          run: |
-            echo "::error title=Tests failed::Some tests or checks have failed"
-            exit 1
